### ISSUE TITLE
Perforce password (P4PASSWD) invalid or unset :<

### ISSUE THREAD

**Issue by connekta** [saadbruno/perforce-discord-webhook#3]
Hello! I've been trying to get this to work, even though I have noooo idea what I'm doing when it comes to these kinds of setups.
I figured I'd ask for help, I've looked through the other 2 issues that has been resolved but I can't verify my issues the same way as they did as I don't have a "p4dctl.conf.d/master.conf" (guessing since I'm not running p4dctl to run my servers?)

I think I've set up the trigger correctly as I see it with the p4 logging options in p4v, but the main issue I have is that I'm getting 
"Perforce password (P4PASSWD) invalid or unset", which I'm guessing is the root of the issue.

If I run the " ./perforce_discord_webhook.sh x x"-command it sends the msg to discord :S

Any advice in how I can debug this thing? Been trying for a couple of days now to get it working but no luck:D
![image](https://user-images.githubusercontent.com/14239508/150659010-196c185e-fe1e-45b3-bd4d-b4cc43f92431.png)

**Comment by saadbruno** [comment]
Hey, sorry for the late response.

Regardless of running perforce via p4dctl or not, you can see in the debug section that you are indeed running the server as the `perforce` user.

The first thing that comes to mind is to make sure that, when issuing the `p4 login` command, you're also doing that using the `perforce` user, otherwise it won't work.

In other words, make sure your bash prompt is showing `perforce@hostname:~$ p4 login` by running `sudo su perforce`.

If that is not the issue, then we can dig deeper, but i'm almost sure that's the issue.

----

I've also been researching ways to auto-login when running the trigger, but I haven't found a way to do it without storing the password in plain text, which is not secure. 

There's [this answer](https://stackoverflow.com/a/45304180) on stackoverflow suggesting md5 hashed passwords, but i haven't tested it.
If you wanna try it, you can put those around line 18 on the `perforce_discord_webhook.sh`:
```
p4 set P4PORT=ssl:localhost:1666
p4 set P4USER=your.username
p4 set P4PASSWD=MD5_hashed_password
```

and see it it works, but i highly discourage it.

**Comment by connekta** [comment]
Hey saadbruno! 

I did however find a way to make it work, it's fugly AF and I think if this would be a more important server than just a hobby-project I would never dare, but by adding the login credentials in the p4-command in the perforce_discord_webhook.sh with -u XX -P XXX it works as intended!

Edit: Thanks for this script by the way!

**Comment by connekta** [comment]
Though while I have you, do you know what I would have to change in order to get the bot to only write out the username and not with the workspace as well?
Currently getting:
"Change 108 by my.name@my.name_workspace" would rather cut it at the @

Also many thanks for this script! Now that it works it'll save my small team a bunch of time in communication
